# Generated by Django 5.2.14 on 2026-06-05 19:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legal_name', models.CharField(max_length=160)),
                ('trade_name', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='printers/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='printers/banners/')),
                ('rccm_number', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('BJ', 'Bénin'), ('TG', 'Togo'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('NE', 'Niger'), ('CM', 'Cameroun'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('FR', 'France'), ('ZZ', 'Autre')], default='CI', max_length=8)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=6)),
                ('daily_capacity_units', models.PositiveIntegerField(default=1000)),
                ('current_load_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('response_time_minutes', models.PositiveIntegerField(default=60)),
                ('kyc_status', models.CharField(default='pending', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente KYB'), ('active', 'Actif'), ('probation', 'En probation'), ('suspended', 'Suspendu'), ('banned', 'Banni')], default='pending', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text="{'mon': {'open': '08:00', 'close': '18:00'}, ...}")),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_profile', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='subscriptions.subscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imprimeur',
                'verbose_name_plural': 'Imprimeurs',
            },
        ),
        migrations.CreateModel(
            name='PrinterProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('setup_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('daily_capacity', models.PositiveIntegerField(default=1000)),
                ('standard_lead_time_days', models.PositiveIntegerField(default=3)),
                ('express_lead_time_days', models.PositiveIntegerField(default=1)),
                ('express_surcharge_pct', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5)),
                ('supported_formats', models.JSONField(blank=True, default=list)),
                ('supported_finishes', models.JSONField(blank=True, default=list)),
                ('supported_papers', models.JSONField(blank=True, default=list)),
                ('custom_options', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_express_available', models.BooleanField(default=False)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_offerings', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printer_products', to='printers.printerprofile')),
            ],
            options={
                'ordering': ['-is_active', '-orders_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrinterAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(default='operator', max_length=64)),
                ('can_manage_orders', models.BooleanField(default=True)),
                ('can_manage_pricing', models.BooleanField(default=False)),
                ('can_manage_team', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_agent', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='printers.printerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('offset', 'Offset'), ('digital', 'Numérique'), ('large_format', 'Grand format'), ('screen', 'Sérigraphie'), ('flexo', 'Flexographie'), ('finishing', 'Finition'), ('binding', 'Reliure')], max_length=24)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('max_format', models.CharField(blank=True, help_text='ex: 70x100, A3, B2…', max_length=32)),
                ('capacity_per_hour', models.PositiveIntegerField(default=0)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='printers.printerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('setup_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishes', to='printers.printerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('BJ', 'Bénin'), ('TG', 'Togo'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('NE', 'Niger'), ('CM', 'Cameroun'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('FR', 'France'), ('ZZ', 'Autre')], max_length=8)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('free_above_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estimated_delay_hours', models.PositiveIntegerField(default=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='printers.printerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('lead_time_days_min', models.PositiveIntegerField(default=1)),
                ('lead_time_days_max', models.PositiveIntegerField(default=5)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(default=100000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capable_printers', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='printers.printerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='printerprofile',
            index=models.Index(fields=['status', 'country'], name='printers_pr_status_004dad_idx'),
        ),
        migrations.AddIndex(
            model_name='printerprofile',
            index=models.Index(fields=['quality_score'], name='printers_pr_quality_0da056_idx'),
        ),
        migrations.AddIndex(
            model_name='printerprofile',
            index=models.Index(fields=['is_featured', 'status'], name='printers_pr_is_feat_214e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='printerproduct',
            index=models.Index(fields=['printer', 'is_active'], name='printers_pr_printer_5f34cc_idx'),
        ),
        migrations.AddIndex(
            model_name='printerproduct',
            index=models.Index(fields=['product', 'is_active'], name='printers_pr_product_f013fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='printerproduct',
            constraint=models.UniqueConstraint(fields=('printer', 'product'), name='uq_printer_product'),
        ),
        migrations.AddConstraint(
            model_name='finish',
            constraint=models.UniqueConstraint(fields=('printer', 'code'), name='uq_printer_finish'),
        ),
        migrations.AddConstraint(
            model_name='productioncapability',
            constraint=models.UniqueConstraint(fields=('printer', 'category'), name='uq_printer_category'),
        ),
    ]
