# Generated by Django 5.2.14 on 2026-06-05 19:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA BCEAO'), ('XAF', 'Franc CFA BEAC'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('NGN', 'Naira'), ('GHS', 'Cedi')], default='XOF', max_length=8)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5)),
                ('max_active_orders', models.PositiveIntegerField(default=10)),
                ('max_team_members', models.PositiveIntegerField(default=2)),
                ('max_products', models.PositiveIntegerField(default=20)),
                ('ai_messages_per_month', models.PositiveIntegerField(default=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=16)),
                ('status', models.CharField(choices=[('trial', 'Essai gratuit'), ('active', 'Active'), ('past_due', 'Impayée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='trial', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subscriber', 'status'], name='subscriptio_subscri_90d254_idx'), models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_3d1ac5_idx')],
            },
        ),
    ]
