# Generated by Django 5.2.14 on 2026-06-05 19:53

import apps.accounts.models
import django.contrib.postgres.indexes
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('primary_role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin Plateforme'), ('support', 'Support'), ('printer', 'Imprimeur'), ('printer_agent', 'Agent Imprimeur'), ('quality_controller', 'Contrôleur Qualité'), ('customer', 'Client Particulier'), ('customer_corporate', 'Client Entreprise'), ('accountant', 'Comptable'), ('courier', 'Livreur')], db_index=True, default='customer', max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('kyc_level', models.PositiveSmallIntegerField(choices=[(0, 'Visiteur'), (1, 'Email vérifié'), (2, 'Téléphone vérifié'), (3, 'Identité vérifiée'), (4, 'Renforcée (entreprise)')], default=0)),
                ('country', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('BJ', 'Bénin'), ('TG', 'Togo'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('NE', 'Niger'), ('CM', 'Cameroun'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('FR', 'France'), ('ZZ', 'Autre')], default='CI', max_length=8)),
                ('locale', models.CharField(default='fr', max_length=8)),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=64)),
                ('preferred_currency', models.CharField(choices=[('XOF', 'Franc CFA BCEAO'), ('XAF', 'Franc CFA BEAC'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('NGN', 'Naira'), ('GHS', 'Cedi')], default='XOF', max_length=8)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('moov', 'Moov Money'), ('card_stripe', 'Carte (Stripe)'), ('bank_transfer', 'Virement bancaire')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=64)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('masked_account', models.CharField(blank=True, max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('shipping', 'Livraison'), ('billing', 'Facturation'), ('pickup', 'Retrait')], default='shipping', max_length=16)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('BJ', 'Bénin'), ('TG', 'Togo'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('NE', 'Niger'), ('CM', 'Cameroun'), ('GA', 'Gabon'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('FR', 'France'), ('ZZ', 'Autre')], default='CI', max_length=8)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=16)),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['primary_role', 'is_active'], name='accounts_us_primary_576b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country', 'primary_role'], name='accounts_us_country_01df2f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='accounts_us_metadat_51cd23_gin'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'kind', 'is_default'], name='accounts_pa_user_id_a2095d_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False)), fields=('user', 'kind', 'phone_number'), name='uq_user_kind_phone'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'kind', 'is_default'], name='accounts_us_user_id_b55d99_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'fcm_token'), name='uq_user_fcm'),
        ),
    ]
